### ISSUE TITLE
Q: Bit-perfect output

### ISSUE THREAD

**Issue by larsoner** [spatialaudio/python-rtmixer#20]
I want to be able to reliably get 32-bit integer values out of the sound card digital channel, such as `256` or `1024` (or higher powers of 2). This is problematic because `float32` cannot represent all integers up to `2 ** 31 - 1` without losing precision:
```
np.float32(2 ** 31 - 1) == np.float32(2147483647) == 2147483600
```
So far I've tried staying in `float64` precision and scaling by `1. / float(2 ** 31 - 1)` to try to avoid as much precision loss as possible before forcing into `float32` format for `rtmixer` but it seems like some triggers are still being missed.

Using `sounddevice` and `int32` format does not suffer from this problem. Hence more reliable solutions for `rtmixer` would be:

1. Support `double`, which can represent 32-bit integers without loss of precision, and be careful about conversion to `int32` for `PortAudio` (or whatever format it wants, not sure if it will take `double` directly and convert).
2. Support `int32` directly.

(2) seems more in line with what `sounddevice` does, in that it already supports `int32` format directly, so seems like a path of least resistance.

Either way, we could duplicate all callback code to achieve double or int32 this but it's ugly. To avoid code dup it seems reasonable to move to Cython (my preference) or C++ templates (I probably could not do this) for the callback implementation. If this seems reasonable, I can try:

1. Converting the current C code to Cython using `cdef` in one PR (don't change functionality, just change how the code is written and compiled), then
2. Use Cython [fused types](https://cython.readthedocs.io/en/latest/src/userguide/fusedtypes.html) to implement an `int32` callback.

Thoughts @mgeier ?

**Comment by mgeier** [comment]
My original goal with the `rtmixer` module was to create a small example for how a callback function implemented in C (and communicating with Python code via PortAudio ringbuffers) can be used with the `sounddevice` module.

It should be just a quick example, but it turned out to be much more elaborate and complicated then I initially expected.

To keep it simple, I decided to only support `float32`, because that's common in audio processing.

PortAudio doesn't support `float64`, so we would have to manually convert from `int32`.
I guess this would work, but it adds complexity to the code and maybe some minor runtime overhead.

I think this is a very special situation, so I don't think it is worth jumping through hoops for this.

BTW, what device are you using that even provides more than 24 bits of accuracy?

> we could duplicate all callback code to achieve double or int32 this but it's ugly.

Exactly.

The C callback function is already much longer and much more complicated than I would have hoped. Duplicating everything for multiple data types would certainly not help making it leaner.

> it seems reasonable to move to Cython (my preference) or C++ templates (I probably could not do this) for the callback implementation.

Well yes, I think either one would be reasonable for a project that needs a custom compiled callback function.

However, I would really like to keep this project as an example for how to use an actual C implementation and keep the dependencies and build complications to a minimum.

I would be very interested in seeing a callback function implemented in Cython, but I wouldn't want to throw away the C example.

What about creating a separate project?
It could start as a fork of this one, but probably it would be easier to start from scratch.

I'm currently looking into Rust, and I already played with the idea of starting a similar project with a callback function implemented in Rust.

I think it would be great to have several examples for callback functions implemented in different compiled languages!

This was also the reason why I made https://github.com/spatialaudio/python-pa-ringbuffer a separate project (see #3 and #5), so the ring buffer can be re-used easily between projects.

**Comment by larsoner** [comment]
> BTW, what device are you using that even provides more than 24 bits of accuracy?

We only get 24 bit in the end and use the higher-order bits (e.g. `1 << 8`) in `int32` mode. It's an RME card FWIW.

> What about creating a separate project?

Sure, sounds reasonable to me. I'll go that route then!

**Comment by mgeier** [comment]
> We only get 24 bit in the end

Then it should be possible to get the "bit-perfect" values you want.

I've never done this myself, but theoretically you should be able to get a 1:1 mapping from `float32` (in the range of +-1.0) as provided by the RME card to 24-bit integers.
The only problem might be that the value `+1.0` cannot be represented, but that's a general problem of (two's complement) signed integers I guess.
It would be interesting if the RME card ever produces a value of `+1.0`.

That's one of those theoretical things that I always wanted to try in practice, but up to now I haven't done it. Please let me know if you find out more details!

> I'll go that route then!

I'm looking forward to that!

But please don't do it just because of this "bit-perfect" thing, because then it might be a waste of time.

**Comment by larsoner** [comment]
> Then it should be possible to get the "bit-perfect" values you want.

Yeah this makes sense, and at least from a quick search through the code (on a GH mirror) it looks like the opposite of `2 ** 32 - 1` (a.k.a. `0x7FFFFFFF`) should be the correct conversion:

https://github.com/EddieRingle/portaudio/blob/9eb5f0b3d820a81d385504d9c54534abbeea1099/src/common/pa_converters.c#L521

The question is, then, is multiplying by `1. / (2 ** 32 -1)` in `float64` then truncating to `float32` the right thing to do...? It's at least hopefully the inverse of this one (non-clipped path?):

https://github.com/EddieRingle/portaudio/blob/9eb5f0b3d820a81d385504d9c54534abbeea1099/src/common/pa_converters.c#L465

That said, we did some trial experiments and some of these bits got "lost" for some reason. We need to figure out why... One complication is that our use case does involve having multiple sounds playing simultaneously that should add (e.g., one could have a 256 and another a 512 and just these two bits should end up active). But it does not seem like it should matter, and in the testing we did it doesn't seem like it should have overlapped. I wonder if the stimulus somehow did not get played at all.

Rather than messing around with this and trying to get these things to all work together properly, it seemed like a safer bet to just move to `int32`, even though it will be more work. But maybe not. Maybe there is some other bug causing just some of these "bits" to get lost.

FWIW it looks like the situation in PsychPortAudio is probably worse, since they have a magical scale factor PA_ANTICLIPGAIN to avoid clipping that would need to be accounted for, too:

https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/master/PsychSourceGL/Source/Common/PsychPortAudio/PsychPortAudio.c#L202-L214

**Comment by mgeier** [comment]
I'm not sure if those float-multiplications do the right thing in all cases ...

I would try to look at the actual bit patterns, see e.g. https://stackoverflow.com/a/31324264/, and try to convert to integers from there.

Theoretically, only one exponent would ever be in use, right?

Now that you've got me interested, could you please provide a short `float` WAV file (or whatever file type you use) containing some of the values you were talking about?
And probably also the `float` values converted from the 24-bit integers `-1`, `0`, `1`, and the maximum/minimum, if possible?
And ideally, for comparison, a recording from an analogue source (with noise and everything) done with the same RME sound card?

> multiple sounds playing simultaneously that should add (e.g., one could have a 256 and another a 512 and just these two bits should end up active)

Sounds like you are ab-using audio infrastructure for non-audio stuff ...

Anyway, I'm not sure if adding `floats` will work or not, but probably it should?
As long as there is no multiplication/division involved and everything stays within the same exponent, there shouldn't be any rounding errors, right?

> it seemed like a safer bet to just move to `int32`, even though it will be more work. But maybe not.

Well, that's of course your call. I just wanted to make sure that you know about the `float` to 24-bit PCM thing.

> PA_ANTICLIPGAIN

OK, that will probably ruin your use case.

That's again the good old "`+1.0` is not representable" problem.
I don't know if there really (still) is a bug in PortAudio. But if there is, I think it should be fixed in PortAudio itself, not in downstream projects.

Some interesting links to that topic:
http://blog.bjornroche.com/2009/12/int-float-int-its-jungle-out-there.html
http://blog.bjornroche.com/2009/12/linearity-and-dynamic-range-in-int.html

**Comment by larsoner** [comment]
> Theoretically, only one exponent would ever be in use, right?

Not sure, my float storage and arithmetic knowledge has faded...

> Now that you've got me interested, could you please provide a short float WAV file (or whatever file type you use) containing some of the values you were talking about?

It's not WAV, it's constructed on the fly for a psychophysics experiment (hence also the emphasis on timing veracity). The conversion I'm currently using is:
```
trigs = [1, 2, 4, 8]
trig_scale = 1. / float(2 ** 32 - 1)
trigs = ((np.array(trigs, int) << 8) *
          trig_scale).astype(np.float32)
```
Then these values get put directly into an `np.zeros(shape, np.float32)` array where each one is high/on for some number of milliseconds, then zero for that duration, etc., so the "sound" ends up looking like this (without the `trig_scale` line to convert it):

```
>>> import numpy as np
>>> x = np.zeros(4410, int)
>>> fs = 44100
>>> t = np.arange(4410) / fs
>>> n = int(0.005 * fs)
>>> x[:n] = 1 << 8
>>> x[n*2:n*3] = 2 << 8
>>> x[n*4:n*5] = 4 << 8
>>> x[n*6:n*7] = 8 << 8
>>> plt.plot(t, x)
```

![Figure_1](https://user-images.githubusercontent.com/2365790/64723849-49874080-d49f-11e9-897a-77def9786f1f.png)

It seems to work, at least most of the time. Still looking into why it's only some of the time, it should be always or never (assuming dithering is off). It's possible my accounting of when the triggers should actually occur (based on when I make `trigs` and tell `rtmixer` to play the "sound")

> Sounds like you are ab-using audio infrastructure for non-audio stuff ...

No not A/B :) Basically we want to be able to "stamp triggers" at arbitrary times during an experiment (possibly overlapping, and *critically* a trigger aligned with when a sound starts). Basically as long as we git e.g. bits 1+2 out at the SPDIF level of the sound card (so 256+512 in int32 to PortAudio), it works.

**Comment by larsoner** [comment]
BTW it looks like the bit perfect output is working now. The dropped boxcars came from errantly emitting a cancel action on the sound playback too early under some circumstances.

**Comment by mgeier** [comment]
Oh, cool, that's great news!
